name: Build and Publish
on:
  release:
    types: [ published ]
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF#refs/*/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ghcr.io/$GITHUB_REPOSITORY:${GITHUB_REF#refs/*/}
